import rawSchema from "../../../data/p21-schema.json";

// Typed lookup over the bundled P21 schema snapshot. The JSON is generated by
// scripts/build-p21-catalog.mjs from docs/P21_Schema.md (which in turn comes
// from scripts/droplet/dump-p21-schema.sh on the egress droplet). Re-run both
// when P21 publishes new views.
//
// The describeView tool reads through here so the model can introspect any
// view's column shape without paying for a live P21 round-trip.

export type SchemaColumn = {
  name: string;
  type: string;
  nullable: boolean;
  key: boolean;
};

export type SchemaView = {
  name: string;
  columns: SchemaColumn[];
};

const VIEWS_BY_NAME: ReadonlyMap<string, SchemaView> = new Map(
  (rawSchema as SchemaView[]).map((v) => [v.name, v]),
);

export function getViewSchema(viewName: string): SchemaView | undefined {
  return VIEWS_BY_NAME.get(viewName);
}

export function allViewNames(): string[] {
  return Array.from(VIEWS_BY_NAME.keys());
}
